onboarding = false

[theme]
name = "terminal"

[terminal]
new_cwd = "follow"
shell_mode = "auto"

[keys]
prefix = "ctrl+b"
switch_workspace = "prefix+shift+1..9"
previous_agent = "prefix+comma"
next_agent = "prefix+period"
last_pane = "prefix+backtick"

[ui]
sidebar_width = 28
sidebar_collapsed_mode = "compact"
agent_panel_sort = "priority"
mouse_capture = true
copy_on_select = true
confirm_close = true
prompt_new_tab_name = true
pane_borders = true
pane_gaps = true
show_agent_labels_on_pane_borders = true
hide_tab_bar_when_single_tab = true

[ui.toast]
delivery = "herdr"
delay_seconds = 2

[ui.sound]
enabled = false

[session]
resume_agents_on_restore = true

[worktrees]
directory = "~/.herdr/worktrees"

[[keys.command]]
key = "prefix+alt+e"
type = "shell"
command = 'editprompt toggle --mux herdr --target-pane "$HERDR_ACTIVE_PANE_ID" --editor nvim --always-copy --pane-rows 12'
description = "open prompt editor"

[[keys.command]]
key = "prefix+alt+g"
type = "popup"
command = "lazygit"
description = "Open lazygit"

[[keys.command]]
key = "prefix+alt+y"
type = "popup"
command = "yazi"
description = "Open yazi"

[[keys.command]]
key = "prefix+alt+j"
type = "popup"
command = "jjui"
description = "Open jjui"
