[tools]
node = "latest"
python = "3.13"
pipx = "latest"
"aqua:orangekame3/stree" = "latest"
"aqua:k1LoW/runn" = "latest"
"npm:editprompt" = "latest"
"npm:mdjanai" = "latest"
"npm:@aws-amplify/cli" = "latest"
"npm:difit" = "latest"
"cargo:octorus" = "latest"
"cargo:atusy/kakehashi" = "latest"
"npm:gut-cli" = "latest"
"npm:@hummer98/cmux-team" = "latest"
"aqua:erikjuhani/basalt" = "latest"
flutter = "latest"
"npm:context-mode" = "latest"
"pipx:graphifyy" = "latest"
"aqua:k1LoW/roots" = "latest"
fnox = "latest"
"go:github.com/myuron/lazycwl" = "latest"
"pipx:markitdown-mcp" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
